site_name: Exhibit
nav:
    - User Guide:
        - 'Overview': 'index.md'
        - 'Installation': 'installation.md'
        - 'Managed App Config': 'app-config.md'
        - 'Content Playlist': 'playlist.md'
        - 'Demo Content': 'demo.md'
    - About:
        - 'Release Notes': 'release-notes.md'
        - 'Known Issues': 'known-issues.md'
        - 'Contact and Support': 'contact.md'
theme: readthedocs
